spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/querydsl
    username: root
    password: tjrwn12

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show_sql: true # ?? System.out.print? ??

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
